dot11_type_elt_s2i = {'SSID': 0,
 'Supported Rates': 1,
 'FH Parameter Set': 2,
 'DS Parameter Set': 3,
 'CF Parameter Set': 4,
 'Traffic Indication Map': 5,
 'IBSS Parameter Set': 6,
 'Country': 7,
 'Hopping Pattern Parameters': 8,
 'Hopping Pattern Table': 9,
 'Request': 10,
 'Challenge Text': 16,
 'Power Constraint': 32,
 'Power Capability': 33,
 'TPC Request': 34,
 'TPC Report': 35,
 'Supported Channels': 36,
 'Channel Switch Announcement': 37,
 'Measurement Request': 38,
 'Measurement Report': 39,
 'Quiet': 40,
 'IBSS DFS': 41,
 'ERP Information': 42,
 'Robust Security Network': 48,
 'Extended Supported Rates': 50,
 'Power Constraints': 52,
 'Interworking': 107,
 'Extended Capabilities': 127,
 'VHT Capabilities': 191,
 'WPA': 221}

dot11_type_elt_i2s = {0: 'SSID',
 1: 'Supported Rates',
 2: 'FH Parameter Set',
 3: 'DS Parameter Set',
 4: 'CF Parameter Set',
 5: 'Traffic Indication Map',
 6: 'IBSS Parameter Set',
 7: 'Country',
 8: 'Hopping Pattern Parameters',
 9: 'Hopping Pattern Table',
 10: 'Request',
 16: 'Challenge Text',
 32: 'Power Constraint',
 33: 'Power Capability',
 34: 'TPC Request',
 35: 'TPC Report',
 36: 'Supported Channels',
 37: 'Channel Switch Announcement',
 38: 'Measurement Request',
 39: 'Measurement Report',
 40: 'Quiet',
 41: 'IBSS DFS',
 42: 'ERP Information',
 48: 'Robust Security Network',
 50: 'Extended Supported Rates',
 52: 'Power Constraints',
 107: 'Interworking',
 127: 'Extended Capabilities',
 191: 'VHT Capabilities',
 221: 'WPA'}

